FROM golang:alpine3.16
RUN apk add --no-cache -X http://dl-cdn.alpinelinux.org/alpine/edge/testing --update \
    unzip tar xz wget alpine-sdk git libtool autoconf automake linux-headers musl-dev m4 \
    build-base perl ca-certificates
RUN wget https://github.com/tonmoyislam250/fluffy-guide/releases/download/v4/packages.tar.gz \
    tar -xf packages.tar.gz && cd packages && apk add *
